version: '2'

services:
  db:
    container_name: db_task2
    image: mysql
    ports:
      - 33071:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  app-network:
    driver: bridge